spring:
#  datasource:
#    url: jdbc:h2:mem:productdb
#    username: sa
#    password:
  sql:
    init:
      mode: always
  jpa:
    show-sql: true
    open-in-view: false
    defer-datasource-initialization: true
    properties:
      hibernate:
        show_sql: true
        use_sql_comments: true
        format_sql: true

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:8761/eureka


#  datasource:
#    url: jdbc:h2:mem:productdb;IFEXISTS=FALSE
#    username: sa
#    password:
#  #    initialization-mode: always  # deprecated
#  sql:
#    init:
#      mode: always
#  jpa:
#    #    show-sql: true
#    open-in-view: false
#    defer-datasource-initialization: true
#    properties:
#      hibernate:
#        show_sql: true
#        use_sql_comments: true
#        format_sql: true


