spring:
  application:
    name: CONFIG-SERVER-SERVICE
  cloud:
    config:
      server:
        git:
          uri: https://github.com/tiagoamp/microservices-series
          search-paths: configs
server:
  port: 8084


